info:
  description: "Service for Customer CRUD operations"

spring:
  application:
    name: customer-service
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/OMS

security:
  basic:
    enabled: false
logging:
  level: error
server:
  port: 9091
    #com.oms.cutomer: debug